### ISSUE TITLE
ERROR: dependency 'processx' is not available for package 'callr' while installing pkgdown and failed

### ISSUE THREAD

**Issue by amrrs** [hadley/pkgdown#442]
Hi, I tried installing `callr` manually too (which is successful) but once again while installing `pkgdown` this fails. 

```
> install_github('hadley/pkgdown')
Downloading GitHub repo hadley/pkgdown@master
from URL https://api.github.com/repos/hadley/pkgdown/zipball/master
Installing pkgdown
Installing 1 package: callr
Installing package into ‘C:/Users/Sabi/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/callr_1.0.0.zip'
Content type 'application/zip' length 36567 bytes (35 KB)
downloaded 35 KB

package ‘callr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Sabi\AppData\Local\Temp\RtmpSw8VPw\downloaded_packages
Downloading GitHub repo r-lib/pkgload@master
from URL https://api.github.com/repos/r-lib/pkgload/zipball/master
Installing pkgload
Downloading GitHub repo r-lib/pkgbuild@master
from URL https://api.github.com/repos/r-lib/pkgbuild/zipball/master
Installing pkgbuild
Downloading GitHub repo r-lib/callr@HEAD
from URL https://api.github.com/repos/r-lib/callr/zipball/HEAD
Installing callr
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/Sabi/AppData/Local/Temp/RtmpSw8VPw/devtools126c85d4f49c3/r-lib-callr-aa1314a"  \
  --library="C:/Users/Sabi/Documents/R/win-library/3.2" --install-tests 

ERROR: dependency 'processx' is not available for package 'callr'
* removing 'C:/Users/Sabi/Documents/R/win-library/3.2/callr'
Error: Command failed (1)
```
SessionInfo:

```
> session_info()
Session info ----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, mingw32             
 ui       RStudio (0.99.451)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Calcutta               
 date     2017-11-05                  

Packages --------------------------------------------------------------------------------------------------
 package   * version date       source        
 curl        0.9.3   2015-08-25 CRAN (R 3.2.2)
 devtools  * 1.12.0  2016-06-24 CRAN (R 3.2.5)
 digest      0.6.12  2017-01-27 CRAN (R 3.2.5)
 git2r       0.18.0  2017-01-01 CRAN (R 3.2.5)
 httr        1.2.1   2016-07-03 CRAN (R 3.2.5)
 lubridate * 1.5.6   2016-04-06 CRAN (R 3.2.5)
 magrittr    1.5     2014-11-22 CRAN (R 3.2.1)
 memoise     1.1.0   2017-04-21 CRAN (R 3.2.5)
 R6          2.2.0   2016-10-05 CRAN (R 3.2.5)
 stringi     1.0-1   2015-10-22 CRAN (R 3.2.2)
 stringr     1.0.0   2015-04-30 CRAN (R 3.2.5)
 withr       1.0.2   2016-06-20 CRAN (R 3.2.5)
> 
```
Could someone please help me fixing this?

**Comment by maurolepore** [comment]
Have you tried installing __processx__ (https://github.com/r-lib/processx)?

**Comment by amrrs** [comment]
Yes i did and but didn't help.

**Comment by amrrs** [comment]
Sorry, the entire problem fixed by updating my R to the latest version!

**Comment by shudras** [comment]
I've updated it to the latest version 3.6.1 but it still does not work. Any suggestions?
May it be because I've installed RTools not in C: but in C:/Program Files/R ?
